### ISSUE TITLE
Enhancement Cloud-Watch metric warnings/loggings

### ISSUE THREAD

**Issue by tijko** [tbenthompson/anti_forgetful#4]
I was hoping to possibly have a variety of `cloud-watch` metrics monitored.  If need be the instance could then premptively log warnings to stdout or where ever.  

I'm not sure if this is out of scope for this particular project or not but I see it as going hand and hand with not leaving the `ec2` instance running.

**Comment by tbenthompson** [comment]
That sounds cool! If you ever whip something up, I'd love to see it.

**Comment by tijko** [comment]
Alright, awesome!  I was hoping you would be receptive to this kind of functionality.

I have a couple of things I am doing but I should be able to get something going a little later on tonight.
